# Generated by Django 3.0.9 on 2020-08-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_models', '0005_auto_20200823_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='street_address',
            field=models.CharField(default='Machava', max_length=255),
            preserve_default=False,
        ),
    ]
