# Generated by Django 3.0.9 on 2020-08-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_models', '0006_billingaddress_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='test-product-1'),
            preserve_default=False,
        ),
    ]
