# Generated by Django 3.0.9 on 2020-08-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_models', '0009_auto_20200823_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='site_models.OrderProduct'),
        ),
    ]
