# Generated by Django 3.0.9 on 2020-08-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_models', '0011_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
