# Generated by Django 3.0.9 on 2020-08-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_models', '0012_auto_20200823_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
