# Generated by Django 3.0.9 on 2021-01-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_models', '0016_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='content',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
