# Generated by Django 3.0.9 on 2021-01-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_models', '0020_currentproductstore_date_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
