# Generated by Django 3.0.9 on 2021-01-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_models', '0023_auto_20210111_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentproductstore',
            name='ordered_product',
        ),
        migrations.AddField(
            model_name='currentproductstore',
            name='ordered_product',
            field=models.ManyToManyField(to='site_models.Order'),
        ),
    ]
