# Generated by Django 3.0.9 on 2021-01-11 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_models', '0024_auto_20210111_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentproductstore',
            options={'ordering': ('-id',)},
        ),
    ]
